### ISSUE TITLE
ConditionalDiagonalNormal sampling doesn't work when model is on GPU

### ISSUE THREAD

**Issue by arashabzd** [bayesiains/nflows#8]
Hello,

I am trying to implement a conditional flow model and I use ConditionalDiagonalNormal as the base distribution. The problem I encountered was that when I tried to sample when the model was on gpu I got 'expected device cuda:0 but got device cpu' error. This is because the noise generated by torch.randn is not on gpu. On cpu, it works fine.

https://github.com/bayesiains/nflows/blob/a712b111d152822d6f8caee47ae173dd51320fea/nflows/distributions/normal.py#L116

**Comment by arturbekasov** [comment]
Thank you for filing an issue, @arashabzd. For `ConditionalDiagonalNormal` the fix is simple, actually: we have `means` and `log_stds` to infer parameters from. Same with `DiagonalNormal` which has parameters. I'll push a fix for both.

However, things are more complex with `StandardNormal`, which has neither parameters nor a context model to infer device from. As discussed with @arashabzd over e-mail, I thing the following could work:
1. Update `DiagonalNormal` to allow providing `mean` and `std` 1D tensors, plus a `trainable` flag to decide whether register those as parameters or buffers.
2. Re-implement `StandardNormal` as `DiagonalNormal` with `mean=0`, `std=1` (broadcast so we don't actually need to store repeated values), and `trainable=False`.

Unless there is a better solution.

**Comment by imurray** [comment]
As people have started to use the library, I'd vote against breaking code by removing `StandardNormal`. If you think there's a neater default, perhaps we could deprecate it instead?

Couldn't we just give `StandardNormal` an optional `device` argument? If the user has another `Tensor` called `foo` kicking around, they could pass `device=foo.device`. If what they really want is a standard normal, that doesn't seem any less neat than forcing them to create a `0` or `1` on the correct device to pass in as `mean` or `std`. A `device` argument is more explicit about what we actually need from the caller, so they're more likely to work out what to fix when their code crashes.

It would be nice if we could fit in with a standard mechanism for a PyTorch user to specify a default device for a block of code, such as a context manager. Unfortunately, I don't think PyTorch provides one(?). There is a context manager for the cuda device, but not for setting cpu vs gpu(?).

**Comment by arturbekasov** [comment]
> As people have started to use the library, I'd vote against breaking code by removing `StandardNormal`. If you think there's a neater default, perhaps we could deprecate it instead?

Sorry, I haven't explained this well: I am not suggesting to remove `StandardNormal`, only to implement it via `DiagonalNormal` internally by pre-setting some parameters. Basically:
```
class StandardNormal(DiagonalNormal):
    def __init__(self):
        super().__init__(mean=0, std=1, trainable=False)
```
This shouldn't break any existing code that uses `StandardNormal`. The right device could be inferred in `DiagonalNormal` based on parameters/buffers, and would be changed as a part of `flow.to(device)`.

> Couldn't we just give `StandardNormal` an optional `device` argument? If the user has another `Tensor` called `foo` kicking around, they could pass `device=foo.device`. If what they really want is a standard normal, that doesn't seem any less neat than forcing them to create a `0` or `1` on the correct device to pass in as `mean` or `std`. A `device` argument is more explicit about what we actually need from the caller, so they're more likely to work out what to fix when their code crashes.

Yes, that's an option (although see above for passing `0` and `1` manually: I also think that's unnecessary). A disadvantage is that this is something to do in addition to `flow.to(device)`, and would be unique to `StandardNormal`.

> It would be nice if we could fit in with a standard mechanism for a PyTorch user to specify a default device for a block of code, such as a context manager. Unfortunately, I don't think PyTorch provides one(?). There is a context manager for the cuda device, but not for setting cpu vs gpu(?).

Yes, I am not aware of a context manager for setting a default device, which is unfortunate. One hacky way (which could trivially be turned into a context manager):
```python
torch.set_default_tensor_type('torch.cuda.FloatTensor')
```

We've done this in NSF experiments, which is why these issues keep popping up. If you're careful and use `tensor.new_*` functions (e.g. `inputs.new_zeros` instead of `torch.zeros`) everywhere things typically work out, but then you have corner-cases like this one.

**Comment by imurray** [comment]
All makes sense; thanks for your patience :-). Could we give the `StandardNormal` a dummy parameter (possibly even empty) and pass its `.device` to `torch.randn`? If not, what you're proposing makes sense.

**Comment by arturbekasov** [comment]
> All makes sense; thanks for your patience :-). 

No worries. :-) Thanks for probing!

> Could we give the StandardNormal a dummy parameter (possibly even empty) and pass its .device to torch.randn? If not, what you're proposing makes sense.

Yep, that makes sense, I've toyed with this idea as well. Maybe that's a better immediate fix, with less potential for breaking something. We can then re-consider at a later date if re-implementing as `DiagonalNormal` makes sense conceptually/practically.

**Comment by arturbekasov** [comment]
#9 has been merged now, which should hopefully have solved most of GPU-related issues. Feel free to re-open if your particular issue hasn't been resolved by this, letting us know what transform you're using exactly. Cheers.
